# Generated by Django 4.2.19 on 2025-03-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_remove_student_dob_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='period',
            field=models.CharField(choices=[('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('1:00 - 2:00', '1:00 - 2:00'), ('2:00 - 3:00', '2:00 - 3:00')], default='9:00 - 10:00', max_length=50),
        ),
    ]
