# Generated by Django 4.2.19 on 2025-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_attendancesession_day_alter_attendancesession_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
